version: '3.8'

services:
    dev:
        container_name: health-monitor-api
        build:
            context: .
            # target: development
            dockerfile: ./Dockerfile
        # command: npm run start
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - Health-Monitor-Api_Volume:/usr/src/app
            # - /usr/app/node_modules
        restart: unless-stopped

volumes:
  Health-Monitor-Api_Volume:
    external: true

networks:
    nesjs-network: