version: '3.8'

services:
    dev:
        container_name: user-api
        build:
            context: .
            # target: development
            dockerfile: ./Dockerfile
        command: npm run start
        ports:
            - 5000:5000
        networks:
            - nesjs-network
        volumes:
            - User-Api_Volume:/usr/src/app
            # - /usr/app/node_modules
        restart: unless-stopped

volumes:
  User-Api_Volume:
    external: true

networks:
    nesjs-network: